services:
  devel:
    image: nvidia/cuda:11.7.0-devel-ubuntu22.04
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - .:/opt
